name: Auto Create Pull Request

on:
  push:
    branches:
      - development

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request from development to master
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: development
          title: 'Automated PR from development to master'
          body: 'This PR was automatically created to merge changes from development to master.'
